export const GET_PRODUCTS = "GET_PRODUCTS";
export const SEARCH_BY_NAME = "SEARCH";
export const FILTER_BY_BRAND = "FILTER_BY_BRAND";
export const FILTER_BY_COLOR = "FILTER_BY_COLOR";
export const SORT_BY_PRICE_ASC = "SORT_BY_PRICE_ASC";
export const SORT_BY_PRICE_DESC = "SORT_BY_PRICE_DESC";
export const SORT_BY_DATE_ASC = "SORT_BY_DATE_ASC";
export const SORT_BY_DATE_DESC = "SORT_BY_DATE_DESC";
export const GET_CART = "GET_CART";
export const DELETE_FROM_CART= "DELETE_FROM_CART";
export const ADD_TO_CART = "ADD_TO_CART";
export const GET_TOTAL_AMOUNT_OF_CART = "GET_TOTAL_AMOUNT_OF_CART";
export const IS_DISPLAY_DELETE_MODAL = "IS_DISPLAY_DELETE_MODAL";
export const ACTIVE_SORT = "ACTIVE_SORT";

